# Travis-CI Build for bee2
# see travis-ci.org for details

language: c

branches:
  only:
    - master

env:
  global:
    - secure: "NrH9YMK7hLXQD63bj2AHc3aEN8GbaXndTc/SXVL0dVfPa4Z//LQehOcrRkjn7GyX/RPY0pNCYPVEErB6kZ2DJ70KSxdtS9OctkH+oGRqGdnfh2AcaOiVcVZZwIp3ZFd6pzH7jn8nNc4lvZvCjv9UteRZ9jO1YWPvhJNUzwK4RFPFuMYANT9w3IV8pVe2JuUO3qMJWgxrb4yI15Yj+kxkpqRr6mHusaAQpu0dzKGvpbIT+B4dzAtCIvkDRwlmNtqObDiFIoyxJsYtAi8ez3SGAO4+eTKJsIQ1nkK2QrqWf2eRndAdsxAd5t8FlHB40befC95LkJhB4AF0uhnqcyjDTBN7faLuCDOzDfCsWwaLkR2xZADC0WAlBxgrifluOZ3NSKc+ArlAA4gCiJ7ES9r18SuEHW2A2RjZVQ7M4RO1lCrtYSEP9Xy9UjKkgWa7GFE+9nk7QKeonijfeD6n6KvB6lldWK+49kUSuDuYl52aOgm0TexL8ciFYYvWXpJ3lYgKasvdEvA93oHHDpk8cJ+1EvMb12V3hAciAxeIhipeQQnS4pQX2co22IhCIKrGzFzzp42H80jqEtrCu/xlTiI4SEX7kvKjMQaHDkpXzSTuXgg4ydyW/5TIlHqaQDRI4ek9IosAutbW+DQ8CBPrfWpskTDg3XZAcgflglFwbFOVVZ4="

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
      - COVERITY_SCAN_PROJECT_NAME="$TRAVIS_REPO_SLUG"
      - COVERITY_SCAN_BRANCH_PATTERN="master"
      - COVERITY_SCAN_NOTIFICATION_EMAIL="agievich@gmail.com"
      - COVERITY_SCAN_BUILD_COMMAND_PREPEND="cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_FAST=ON"
      - COVERITY_SCAN_BUILD_COMMAND="make"
      script:
      - curl -s 'https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh' | bash || true
    - os: linux
      compiler: gcc
      env: BUILD_TYPE="Release" BUILD_FAST="ON"  BASH_PLATFORM="BASH_64"
    - os: osx
      compiler: clang
      env: BUILD_TYPE="Release" BUILD_FAST="OFF" BASH_PLATFORM="BASH_32"
    - os: linux
      compiler: gcc
      env: BUILD_TYPE="MemSan" BUILD_FAST="ON" BASH_PLATFORM="BASH_AVX2" 
    - os: osx
      compiler: clang
      env: BUILD_TYPE="Check" BUILD_FAST="OFF" BASH_PLATFORM="BASH_64"
    - os: linux
      compiler: gcc
      env: BUILD_TYPE="Check" BUILD_FAST="ON" BASH_PLATFORM="BASH_AVX512"
    - os: linux
      compiler: gcc
      sudo: required
      env: BUILD_TYPE="Coverage" BUILD_FAST="OFF" BASH_PLATFORM="BASH_64"
      install:
      - sudo apt-get install -y lcov
      after_success:
      - lcov -c -i -d src -o coverage_base.info
      - test/testbee2
      - lcov -c -d src -o coverage_test.info
      - lcov -a coverage_base.info -a coverage_test.info -o coverage.info
      - bash <(curl -s https://codecov.io/bash) -f coverage.info

script: 
  - mkdir build && cd build 
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_FAST=$BUILD_FAST -DBASH_PLATFORM=$BASH_PLATFORM ..
  - make
  - ctest --verbose
